# Workflow name
name: Test

# Start testing on push and pull_request
on: [push, pull_request]

# Testing jobs
jobs:

  # Testing builds
  build:

    # Testing program on
    runs-on: ubuntu-latest

    # Steps
    steps:
      # Add checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Start testing
      - name: Test
        run: |
          python3 pip install -r requirements.txt
          python3 -m pytest tests/*